services:
  app:
    build: .
    ports:
      - target: 8080
        published: 8080
        protocol: tcp
        mode: host
    env_file:
      - .env
    environment:
      # The app expects to use the DATABASE_URL specified in your .env file.
      DATABASE_URL: ${DATABASE_URL}
    depends_on:
      - db
    develop:
      watch:
        # Sync the working directory with "/app" in the container, excluding the virtual environment.
        - action: sync
          path: .
          target: /app
          ignore:
            - .venv/
        # Rebuild the image automatically if the dependency file changes.
        - action: rebuild
          path: ./pyproject.toml

  db:
    image: postgres:latest
    env_file:
      - .env
    ports:
      - target: 5432
        published: 5432
        protocol: tcp
        mode: host
    volumes:
      - ./opt/db:/var/lib/postgresql/data
